### ISSUE TITLE
Using Mongration without AutoConfiguration?

### ISSUE THREAD

**Issue by achuinard** [KuliginStepan/mongration#20] opened 2021-04-26 22:57 UTC
In my Spring Boot project, I had to disable the whole auto-configuration of Mongo since I actually connect to two different instances of Mongo in my application.

```
@SpringBootApplication(exclude = {
        MongoAutoConfiguration.class,
        MongoDataAutoConfiguration.class,
        DataSourceAutoConfiguration.class
})
```

I'd still like to use Mongration though and provide it one of my `MongoTemplate`s to run migrations / versioning against. Do you have any guides on doing this? I thought doing @Import(MongrationConfiguration.class) into my application would help but it doesn't. I can't seem to do anything to get Mongration to run.

Any advice would be appreciated. Thank you!

**Comment by KuliginStepan** [comment] 2021-04-27 10:22
Hi!

If you want to switch off AutoConfiguration completely, you should:
1. Add `MongrationAutoConfiguration.class` to `@SpringBootApplication(exclude={})`
2. Create your own configuration file as follows:
```
@Configuration(proxyBeanMethods = false)
public class CustomMongrationConfiguration {

    @Bean
    public MongrationProperties mongrationProperties() {
        return new MongrationProperties();
    }

    @Bean
    public AbstractMongration mongration(MongrationProperties properties, MongoTemplate mongoTemplate, ApplicationContext context) {
        return new Mongration(properties, mongoTemplate, context);
    }
}
```
3. Ensure that you have at least 1 `MongoTemplate` bean in `ApplicationContext` and one of them is marked as `@Primary`. This "primary" `MongoTemplate` will be used by Mongration.

Leave a comment here if it doesn't help, I will try to investigate it more then.

**Comment by achuinard** [comment] 2021-04-27 14:31
Thanks for the help! I tried that config class though and am getting this:

```
org.springframework.expression.spel.SpelEvaluationException: EL1057E: No bean resolver registered in the context to resolve access to bean 'mongrationProperties'
	at org.springframework.expression.spel.ast.BeanReference.getValueInternal(BeanReference.java:51)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:55)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:91)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getTypedValue(SpelNodeImpl.java:117)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:308)
	at org.springframework.data.mongodb.core.mapping.BasicMongoPersistentEntity.getCollection(BasicMongoPersistentEntity.java:129)
	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexResolver.resolveIndexForEntity(MongoPersistentEntityIndexResolver.java:124)
	at org.springframework.data.mongodb.core.index.MongoPersistentEntityIndexResolver.resolveIndexFor(MongoPersistentEntityIndexResolver.java:104)
	at org.springframework.data.mongodb.core.index.IndexResolver.resolveIndexFor(IndexResolver.java:69)
	at com.kuliginstepan.mongration.service.impl.IndexCreatorImpl.createIndexes(IndexCreatorImpl.java:30)
	at com.kuliginstepan.mongration.AbstractMongration.executeMigration(AbstractMongration.java:132)
	at com.kuliginstepan.mongration.AbstractMongration.lambda$null$0(AbstractMongration.java:53)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4252)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:153)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1782)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:334)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:679)
	at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onComplete(FluxFlattenIterable.java:260)
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:255)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1765)
	at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:121)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:838)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:600)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:580)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:457)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:289)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:225)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:363)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:161)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4252)
	at reactor.core.publisher.Mono.block(Mono.java:1684)
	at com.kuliginstepan.mongration.AbstractMongration.afterSingletonsInstantiated(AbstractMongration.java:55)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:914)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
```

**Comment by achuinard** [comment] 2021-04-27 19:47
If it helps at all I do not use @EnableMongoRepositories anywhere in my application.

**Comment by KuliginStepan** [comment] 2021-04-28 03:57
Could you share your configuration classes related to MongoDB? It seems that you missed something and as a result, `BasicMongoPersistentEntity` didn't has access to `SpelEvalutionContext` with `beanResolver` injected.

**Comment by achuinard** [comment] 2021-04-28 04:02
```
@Configuration
public class MongoConfig {
    private String mongoDbCredentialsSecretPath;
    private String mongoUriSecretsManagerKey;
    private String mongodbAWSCreds;
    private final String db1 = "db1";
    private final String db2 = "db2";

    @Autowired
    public MongoConfig() throws Exception {
        mongodbAWSCreds = "mongodb://mydb:mydb@localhost:27017/mydb";
    }

    @Bean
    @Primary
    public MongoTemplate mongoTemplate(MongoClient mongoClient) {
        return getMongoTemplate(mongoClient, db1);
    }

    @Bean
    public MongoTemplate mongoTemplateDb2(MongoClient mongoClient) {
        return getMongoTemplate(mongoClient, db2);
    }

    @Bean
    public MongoTemplate mongoTemplatePrimaryOnly(MongoClient mongoClient) {
        MongoTemplate mongoTemplate = getMongoTemplate(mongoClient, db1);
        mongoTemplate.setReadPreference(ReadPreference.primary());
        return mongoTemplate;
    }

    @Bean
    public MongoClient mongoClient() {
        return MongoClients.create(mongodbAWSCreds);
    }

    private MongoTemplate getMongoTemplate(MongoClient mongoClient, String databaseName) {
        return new MongoTemplate(new SimpleMongoClientDatabaseFactory(mongoClient, databaseName));
    }
}
```

**Comment by KuliginStepan** [comment] 2021-04-28 04:48
Why you decided to switch off AutoConfiguration? I think that it can be done with following configuration:
```
@Configuration
public class MongoConfig {
    private String mongoDbCredentialsSecretPath;
    private String mongoUriSecretsManagerKey;
    private final String db1 = "db1";
    private final String db2 = "db2";

    @Autowired
    public MongoConfig() throws Exception {
    }

    @Bean
    @Primary
    //MongoDatabaseFactory and MongoConverter will be created by Spring Boot's AutoConfigurations
    public MongoTemplate mongoTemplate(MongoDatabaseFactory factory, MongoConverter converter) {
        return new MongoTemplate(factory, converter);
    }

    @Bean
    //MongoClient will be created by Spring Boot's AutoConfigurations
    public MongoTemplate mongoTemplateDb2(MongoClient mongoClient) {
        return getMongoTemplate(mongoClient, db2);
    }

    @Bean
    //MongoClient will be created by Spring Boot's AutoConfigurations
    public MongoTemplate mongoTemplatePrimaryOnly(MongoClient mongoClient) {
        MongoTemplate mongoTemplate = getMongoTemplate(mongoClient, db1);
        mongoTemplate.setReadPreference(ReadPreference.primary());
        return mongoTemplate;
    }

    private MongoTemplate getMongoTemplate(MongoClient mongoClient, String databaseName) {
        return new MongoTemplate(new SimpleMongoClientDatabaseFactory(mongoClient, databaseName));
    }
}
```
Also turn on all MongoDB related AutoConfigurations. Spring Boot will create all needed beans except `MongoTemplate`, because you specify your own bean in configuration.

**Comment by achuinard** [comment] 2021-04-28 14:31
So I did that and got rid of my AutoConfiguration exclusions - was also able to get rid of my own custom MongrationConfiguration class - and I still get the same exact error.

**Comment by KuliginStepan** [comment] 2021-04-28 14:37
Which versions of mongration and spring boot are you using? I will try to reproduce this issue.

**Comment by achuinard** [comment] 2021-04-28 14:38
Thanks for all your help I'm on Spring Boot 2.3.7 with Mongration 1.3.1.

**Comment by achuinard** [comment] 2021-04-28 14:55
Looking here I see an alternate way you could reference the collection name:

https://stackoverflow.com/questions/41698445/cannot-resolve-bean-in-spel-for-spring-data-mongodb-collection-name

Maybe replace:

```
@Document(collection = "#{@mongrationProperties.getChangelogsCollection()}")
```

With:

```
@Document(collection = "@mongrationProperties.getChangelogsCollection()")
```

?

**Comment by KuliginStepan** [comment] 2021-04-28 17:26
I created minimal working project. It is just one class Spring Boot Application:
```
package com.example.demo;

import com.kuliginstepan.mongration.annotation.Changelog;
import com.kuliginstepan.mongration.annotation.Changeset;
import com.mongodb.ReadPreference;
import com.mongodb.client.MongoClient;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Primary;
import org.springframework.data.mongodb.MongoDatabaseFactory;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.SimpleMongoClientDatabaseFactory;
import org.springframework.data.mongodb.core.convert.MongoConverter;

@SpringBootApplication
@Changelog
public class Demo2Application {

    public static void main(String[] args) {
        SpringApplication.run(Demo2Application.class, args);
    }

    @Changeset(author = "Me", order = 0)
    public void test(MongoTemplate template) {
        
    }

    @Bean
    @Primary
    //MongoDatabaseFactory and MongoConverter will be created by Spring Boot's AutoConfigurations
    public MongoTemplate mongoTemplate(MongoDatabaseFactory factory, MongoConverter converter) {
        return new MongoTemplate(factory, converter);
    }

    @Bean
    //MongoClient will be created by Spring Boot's AutoConfigurations
    public MongoTemplate mongoTemplateDb2(MongoClient mongoClient) {
        return getMongoTemplate(mongoClient, "test1");
    }

    @Bean
    //MongoClient will be created by Spring Boot's AutoConfigurations
    public MongoTemplate mongoTemplatePrimaryOnly(MongoClient mongoClient) {
        MongoTemplate mongoTemplate = getMongoTemplate(mongoClient, "test2");
        mongoTemplate.setReadPreference(ReadPreference.primary());
        return mongoTemplate;
    }

    private MongoTemplate getMongoTemplate(MongoClient mongoClient, String databaseName) {
        return new MongoTemplate(new SimpleMongoClientDatabaseFactory(mongoClient, databaseName));
    }

}
```
with following dependencies:
```
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.github.kuliginstepan:mongration:1.3.1'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
}
```
And `application.properties`:
```
spring.data.mongodb.uri=mongodb://creds@mongodb-0.mongodb-headless.mongodb.svc.cluster.test:27017/myDb
```

It is working as expected. Maybe you have something different in your configuration?
You can email me (Kuligin_stepan@mail.ru) if you want to switch conversation to private.

**Comment by achuinard** [comment] 2021-04-30 14:58
This is why I turned off auto-config - I don't want to use `spring.data.mongodb.uri` since I have 2 different Mongo DBs I'm connecting to. Still trying to get this working, will let you know if I have any luck.

**Comment by KuliginStepan** [comment] 2021-04-30 15:02
Do you have 2 different Mongo DB servers or 2 different DBs on single Mongo DB server?

**Comment by achuinard** [comment] 2021-04-30 15:04
Same server, 2 different MongoTemplate beans, one is @Primary.

**Comment by KuliginStepan** [comment] 2021-04-30 15:24
So why you don't want to use `spring.data.mongodb.uri`? Just put in `spring.data.mongodb.uri` your `@Primary` db and override db name in other MongoTemplate beans

**Comment by achuinard** [comment] 2021-04-30 15:40
Because we use secrets and don't hardcode connection strings in our property files.

![image](https://user-images.githubusercontent.com/469647/116719057-a1422a80-a9a8-11eb-993e-9680b04cb376.png)

Something is up with the context when your bean is trying to be resolved. This `getValueInternal` method works well when trying to resolve other expressions. However, only when trying to resolve for the mongrationProperties bean, everything is `null` under that `state.getEvaluationContext()`.

**Comment by achuinard** [comment] 2021-04-30 16:02
Any thoughts on making a change to the SpEl expression that I linked to earlier on StackOverflow?

**Comment by achuinard** [comment] 2021-04-30 16:44
I definitely think it has something to do with the SpEL in your annotation. I cloned your lib and installed to local snapshot replacing SpEL with a hardcoded collection name. Seems to have worked well. Although publishing locally doesn't work that great because I have no signing configuration.

**Comment by KuliginStepan** [comment] 2021-05-01 12:01
I have published snapshot version `1.3.2-SNAPSHOT`, where I tried to refactor the way how changeset collection name is determined. Does it fix your problem?

**Comment by KuliginStepan** [comment] 2021-05-01 12:04
Snapshot repository url `https://oss.sonatype.org/content/repositories/snapshots`

**Comment by achuinard** [comment] 2021-05-02 20:56
That worked. It created an empty collection called 'changesetEntity' and another called 'mongration_changelogs' with 1 document. Thank you! Is this something you can put on a release branch? Also any idea why the empty `changesetEntity` collection?

**Comment by KuliginStepan** [comment] 2021-05-03 12:41
I have updated library to fix issue with empty `changesetEntity` collection creation. Ensure that it's still working for you and `changesetEntity` collection is not created anymore. If all will be good, I would like to release it as `1.3.2` soon.

**Comment by achuinard** [comment] 2021-05-03 15:24
Worked! I only have `mongration_changelogs` now. Thank you so much! Looking forward to release.

**Comment by KuliginStepan** [comment] 2021-05-04 10:18
1.3.2 has been released! It will be available on maven central within few hours.

**Closed as completed** 2021-05-04 15:30 UTC
Labels: question
